// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema_ventas_quesito_store.Data;

#nullable disable

namespace sistema_ventas_quesito_store.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito");

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.CarritoDetalle", b =>
                {
                    b.Property<int>("IdCarritoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarritoDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdCarrito")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdCarritoDetalle");

                    b.HasIndex("IdCarrito");

                    b.HasIndex("IdProducto");

                    b.ToTable("CarritoDetalles");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Activo = true,
                            Descripcion = "Gorras urbanas y deportivas",
                            NombreCategoria = "Gorras"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Activo = true,
                            Descripcion = "Zapatillas casuales y deportivas",
                            NombreCategoria = "Zapatillas"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Activo = true,
                            Descripcion = "Polos de algodón y lycra",
                            NombreCategoria = "Polos"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Activo = true,
                            Descripcion = "Poleras con y sin capucha",
                            NombreCategoria = "Poleras"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Activo = true,
                            Descripcion = "Jeans, joggers y cargo pants",
                            NombreCategoria = "Pantalones"
                        });
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.DetallePedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetallePedido");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Entrega", b =>
                {
                    b.Property<int>("IdEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntrega"));

                    b.Property<string>("CiudadDestino")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CostoAdicional")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DireccionDestino")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmpresaEnvio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int?>("IdRepartidor")
                        .HasColumnType("int");

                    b.Property<string>("MedioTransporte")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdEntrega");

                    b.HasIndex("IdPedido")
                        .IsUnique();

                    b.HasIndex("IdRepartidor");

                    b.ToTable("Entregas");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.EstadoEntrega", b =>
                {
                    b.Property<int>("IdEstadoEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoEntrega"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEntrega")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdEstadoEntrega");

                    b.HasIndex("IdEntrega");

                    b.ToTable("EstadosEntrega");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoEntrega")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTipoEntrega");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Empleado"
                        },
                        new
                        {
                            IdRol = 3,
                            NombreRol = "Repartidor"
                        },
                        new
                        {
                            IdRol = 4,
                            NombreRol = "Cliente"
                        });
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.TipoEntrega", b =>
                {
                    b.Property<int>("IdTipoEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEntrega"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdTipoEntrega");

                    b.ToTable("TiposEntrega");

                    b.HasData(
                        new
                        {
                            IdTipoEntrega = 1,
                            Descripcion = "El cliente recoge en la tienda de Cajamarca",
                            Nombre = "Recojo en tienda"
                        },
                        new
                        {
                            IdTipoEntrega = 2,
                            Descripcion = "Entrega en dirección del cliente dentro de Cajamarca",
                            Nombre = "Envío a domicilio"
                        },
                        new
                        {
                            IdTipoEntrega = 3,
                            Descripcion = "Envío nacional mediante empresa de transporte",
                            Nombre = "Envío a otra ciudad"
                        });
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Celular = "999999999",
                            Contrasena = "Admin123",
                            Correo = "admin@quesitostore.com",
                            DNI = "00000000",
                            Direccion = "Cajamarca",
                            IdRol = 1,
                            NombreCompleto = "Administrador"
                        });
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Carrito", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Usuario", "Usuario")
                        .WithOne("Carrito")
                        .HasForeignKey("sistema_ventas_quesito_store.Models.Carrito", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.CarritoDetalle", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Carrito", "Carrito")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCarrito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_ventas_quesito_store.Models.Producto", "Producto")
                        .WithMany("CarritoDetalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.DetallePedido", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_ventas_quesito_store.Models.Producto", "Producto")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Entrega", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Pedido", "Pedido")
                        .WithOne("Entrega")
                        .HasForeignKey("sistema_ventas_quesito_store.Models.Entrega", "IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sistema_ventas_quesito_store.Models.Usuario", "Repartidor")
                        .WithMany("Entregas")
                        .HasForeignKey("IdRepartidor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.EstadoEntrega", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Entrega", "Entrega")
                        .WithMany("EstadosEntrega")
                        .HasForeignKey("IdEntrega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Pedido", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Usuario", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sistema_ventas_quesito_store.Models.TipoEntrega", "TipoEntrega")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdTipoEntrega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoEntrega");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Producto", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Usuario", b =>
                {
                    b.HasOne("sistema_ventas_quesito_store.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Carrito", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Entrega", b =>
                {
                    b.Navigation("EstadosEntrega");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Producto", b =>
                {
                    b.Navigation("CarritoDetalles");

                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.TipoEntrega", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("sistema_ventas_quesito_store.Models.Usuario", b =>
                {
                    b.Navigation("Carrito");

                    b.Navigation("Entregas");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
